### ISSUE TITLE
MethodSpec does not correctly override bounded types

### ISSUE THREAD

**Issue by PinkMoustacheMan** [palantir/javapoet#117]
## What happened?

I am trying to create an annotation processor to generate implementations of interfaces using java 23 and javapoet 0.5.0.
Those interfaces contain bounded types such as `<S extends T>` where `T` is a generic type variable that is part of the interface itself (which gets specified with a concrete type using another interface).

These would be the classes I work with.
```
public interface TestService<T> {
    <S extends T> void methodWithBoundedType(S t);
    void methodWithUnboundedType(T t);
}

@GenerateImplementation
public interface TestServiceExtension extends TestService<String> {
    // empty
}
```

The code that is generated looks as follows:
```

public class TestImplementation implements TestServiceExtension {
    @Override
    public <S extends T> void methodWithBoundedType(final S t) {
        // some code
    }

    @Override
    public void methodWithUnboundedType(final String t) {
        // some code
    }
}
```

I would expect it to look as follows. `T` being replaced with whatever type I have specified in my interface
```
public class TestImplementation implements TestServiceExtension {
    @Override
    public <S extends String> void methodWithBoundedType(final S t) {
        // some code
    }

    @Override
    public void methodWithUnboundedType(final String t) {
        // some code    
    }
}
```

Based on what I could debug this does not seem to be intended behaviour of the `MethodSpec.overriding()` Method.
When fetching the `resolvedParameterTypes` on [line 298](https://github.com/palantir/javapoet/blob/ab215f4c2a7849b4afc8a1f91221cd0c01b99dad/javapoet/src/main/java/com/palantir/javapoet/MethodSpec.java#L298), the bounded type `S` with bound `String` is present as expected.
But when creating a `TypeName` from it on [line 306](https://github.com/palantir/javapoet/blob/ab215f4c2a7849b4afc8a1f91221cd0c01b99dad/javapoet/src/main/java/com/palantir/javapoet/MethodSpec.java#L306), the bound is lost as it is changed to `T` rather than `String`.

I have created a small test project that recreates this issue [here](https://github.com/PinkMoustacheMan/javapoet-example/tree/main).

**Comment by ash211** [comment]
@PinkMoustacheMan I think your PR #118 resolves this issue?  I'm going to close this issue, but please reopen if needed.

Once again, thanks for your contributions!
