### ISSUE TITLE
Some `addPermittedSubclass` methods call invalid `addSuperinterface` inside.

### ISSUE THREAD

**Issue by skku-daniilkim** [palantir/javapoet#68]
## What happened?

`TypeSpec.addPermittedSubclass(Type permittedSubclass)` and `TypeSpec.addPermittedSubclass(TypeMirro permittedSubclass)` incorrectly call `TypeSpec.addSuperinterface(... superinterface, boolean avoidNestedTypeNameClashes)` instead of `TypeSpec.addPermittedSubclass(... superinterface, boolean avoidNestedTypeNameClashes)`:

https://github.com/palantir/javapoet/blob/9fb628c4b52ea9ec73ac6cb36dedddda4eba6d9f/javapoet/src/main/java/com/palantir/javapoet/TypeSpec.java#L756-L758

https://github.com/palantir/javapoet/blob/9fb628c4b52ea9ec73ac6cb36dedddda4eba6d9f/javapoet/src/main/java/com/palantir/javapoet/TypeSpec.java#L771-L773

## What did you want to happen?

They should call the `TypeSpec.addPermittedSubclass(... superinterface, boolean avoidNestedTypeNameClashes)`.

**Comment by carterkozak** [comment]
That looks like a bug! Would you like to PR a fix? (I think you’ve opened a pr, but into your own fork)

**Comment by skku-daniilkim** [comment]
Oh yeah, my bad. Fixed the PR.
